apiVersion: v1
kind: ConfigMap
metadata:
  name: central-end-user-registry-config
  labels:
      app: central-end-user-registry
data:
  server.host: "central-end-user-registry.local"
  server.port: "3001"
  default.json: |
    {
      "PORT": 3001,
      "HOSTNAME": "http://central-end-user-registry.local"
    }
  ## default knexfile config
  knexfile.js: |
    'use strict'

    const migrationsDirectory = '/opt/central-end-user-registry/migrations'
    const Config = require('/opt/central-end-user-registry/src/lib/config')
    module.exports = {
      client: 'pg',
      connection: Config.DATABASE_URI,
      migrations: {
        directory: migrationsDirectory,
        tableName: 'migrations',
        stub: `${migrationsDirectory}/migration.template`
      }
    }
